### ISSUE TITLE
Error: upgrade your plan at https://macvendors.com

### ISSUE THREAD

**Issue by openmoto** [TheTaylorLee/AdminToolbox#1]
Hi, 
just found this and trying in out.
Is there a way to add my own API?
`Invoke-NetworkScan xxx.xx.xx.xx/xx -deepscan 

WARNING:  , {"errors":{"detail":"Not Found"}}
WARNING:  , {"errors":{"detail":"Too Many Requests","message":"Please slow down your requests or upgrade your plan at https://macvendors.com"}}`

Thanks

**Comment by TheTaylorLee** [comment]
I would advise download the latest version of that command or the containing module. I updated that command to instead use a list of mac vendors from a text file. That allowed speeding up the returned results for the command.

**Comment by TheTaylorLee** [comment]
Made irrelevant through a previous update.
