### ISSUE TITLE
Get-Info is not working under Windows Powershell 5.1

### ISSUE THREAD

**Issue by crimsonread** [TheTaylorLee/AdminToolbox#101]
**Topic Reason**
Hello, I have installed Admintoolbox in Windows powershell 5.1 but it is not working.
It looks other modules are working but Admintoolbox is not working wheres it is working under Powershell 7.x

**Topic Details**
Get-Info: The term 'Get-Info' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Code Sample**
```PowerShell
#Add any code Samples here
Get-Info

**Additional context**
I would like to know if Admintoolbox functions can be installed in only powershell v 7. Because As I see the module path, Admintoolbox folder is not existed even if installation was completed.

**Comment by TheTaylorLee** [comment]
PowerShell core will install modules in a directory only watched by PowerShell core unless you set the scope when installing the module.

I suggesting looking at the scope parameter of install-module or just install the module again from 5.1 PowerShell.

**Comment by crimsonread** [comment]
> PowerShell core will install modules in a directory only watched by PowerShell core unless you set the scope when installing the module.
> 
> I suggesting looking at the scope parameter of install-module or just install the module again from 5.1 PowerShell.

Great. I installed it again by adding scope parameter which solved issue.
Thanks.
