### ISSUE TITLE
Networking - Invoke-NetworkScan.ps1 - Custom TCP ports

### ISSUE THREAD

**Issue by bscheewe** [TheTaylorLee/AdminToolbox#133]
**Feature Target Details**
- Module Name: Networking
- Existing Function Name: Invoke-NetworkScan.ps1
- New Function Name:

**Describe the solution you'd like**
There are currently 2 groups of ports scanned - either the default or deepscan ports.  Could we either replace the default ports with a requirement to enter ports, or add a 3rd option for custom ports where a comma-delimited list of ports can be entered as a parameter?

**Why is this change needed?**
The need to specify ports that are not in the default list.

**Code Sample**
```
**Code Sample**
.Parameter Ports
    Specify the TCP ports to scan in comma-delimited list.
#
 if ($null -ne $ArpRefresh) {
            if ($Ports) {
                $Script:QuickScan = Invoke-PSnmap -ComputerName $CIDR -Port $Ports -ScanOnPingFail -Dns -NoSummary -PortConnectTimeoutMs 500 -ThrottleLimit $Threads
            }
            if ($DeepScan) {
                $Script:SlowScan = Invoke-PSnmap -ComputerName $CIDR -Port 21, 22, 23, 25, 53, 67, 80, 139, 389, 443, 445, 902, 3389, 9100 -ScanOnPingFail -Dns -NoSummary -PortConnectTimeoutMs 500 -ThrottleLimit $Threads
            }
            else {
                $Script:QuickScan = Invoke-PSnmap -ComputerName $CIDR -Port 21, 22, 23, 80, 443, 3389, 9100 -ScanOnPingFail -Dns -NoSummary -PortConnectTimeoutMs 500 -ThrottleLimit $Threads
            }
        }
```
**Additional context**
None

**Comment by TheTaylorLee** [comment]
If added, this will require another parametersetname and a rewrite to handle the variable output options. I'll consider it after I have time to look at this. You might also check out the module psnmap. This function is just an expansion of that module to add certain scan details.

**Comment by TheTaylorLee** [comment]
- [ ] Need named parameter sets to enforce options
    - [ ] There should be 2 parameter sets.
        - Ports is a parameter set that requires specifying an array of ports.
        - The other parameter set doesn't include ports as an option and would be for deep and light scans
    - [ ] [ValidateSet('Deep', 'Port, 'Light')]
        - "Deepscan" goes away and becomes a scantype option for a validation set
        - "Port" scan is for specifying custom ports
        - "Light" replaces the old default scan options when not choosing a deepscan
- [ ] Need to update the help script block
    - Update the parameter options
    - Update the examples
    - Remove or update existing help block info
- [ ] Will have to modify or add to the process block to handle the custom scan.
    - $Script:Portscan is the new variable created in the begin block for a custom port scan.

**Comment by TheTaylorLee** [comment]
This is now implemented.
