### ISSUE TITLE
Build Pipeline?

### ISSUE THREAD

**Issue by gengle** [TheTaylorLee/AdminToolbox#3]
I am impressed with the quality of your modules - are you willing to share your build pipeline?

**Comment by TheTaylorLee** [comment]
I don't have a defined build pipeline per say, but I tend to follow the below steps prior to publishing to PowerShell Gallery.

1. Need for a function is determined by my current work, the work of a coworker, or an idea I might have.
2. Dependent on the reason for building a script, I create a script, and use/test it within my own environment, or a customers environment. 
3. I take the script I created, convert variables into parameters, and add help sections to the function.
4. I test the function in the same environment where I originally ran the script I created and fix any issues.
5. I add the function to one of the dependent modules.
6. I push the changes to my PSPortable and PSPortableLight GitHub repositories
7. I use the deploy scripts for PSPortable and PSPortableLight to download my changed modules, and confirm the modules load without errors.
8. Upload new module versions to PowerShell Gallery
9. If I find issues later I resolve them and repeat steps 3-8. With step 3 being replaced with changes to the function or functions that have an issue.

Not a typical process I would assume, but this module has been a learning process for me. I created it to learn PowerShell and it has evolved over time.

**Comment by TheTaylorLee** [comment]
https://github.com/TheTaylorLee/AdminToolbox/blob/master/.github/BuildPipeline.md
