### ISSUE TITLE
update-help HelpInfoUri does not resolve to a container

### ISSUE THREAD

**Issue by cinderbdt** [TheTaylorLee/AdminToolbox#59]
`PS C:\Users\cogito-ergo-sum> update-help -UICulture en-US
Update-Help: Failed to update Help for the module(s) 'AdminToolbox.Remoting' with UI culture(s) {en-US} : The value of the
HelpInfoUri key in the module manifest must resolve to a container or root URL on a website where the help files are stored.
The HelpInfoUri 'https://github.com/TheTaylorLee/AdminToolbox/issues' does not resolve to a container.`

**Comment by cinderbdt** [comment]
`PS C:\Users\cogito-ergo-sum> get-installedmodule -name "AdminToolbox.Remoting"

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
1.3.0.0              AdminToolbox.Remoting               PSGallery            Functions for remote management of Endpo…`

**Comment by cinderbdt** [comment]
So I couldn't get update to work, but I see that there's a much newer version. I'll come back to this if it still doesn't work.

**Comment by cinderbdt** [comment]
Same issue using 1.8.2.

**Comment by TheTaylorLee** [comment]
I have not supplied a helpinfouri in the Admintoolbox module manifests. This was not something I ever really considered. The functions always have the most up to date help for the released module version. I could possibly update the existing docs workflow to potentially automate the process of adding xml help. Though I don't view this as an important addition.

https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/create-help-using-platyps?view=powershell-7.2#creating-an-updateable-help-package

Is there specific need for updateable help?

**Comment by TheTaylorLee** [comment]
Resolved the error message using the linked pull request. Workflows will update the manifests and publish to PS Gallery shortly.
